use crate::database::repositories::meeting::MeetingsRepository;
use crate::state::AppState;
use log::{error as log_error, info as log_info};
use serde::{Deserialize, Serialize};
use tauri::Manager;
use tauri_plugin_dialog::DialogExt;

/// Response from exporting a meeting to markdown
#[derive(Debug, Serialize, Deserialize)]
pub struct ExportMarkdownResponse {
    pub file_path: String,
    pub success: bool,
    pub bytes_written: u64,
}

/// Export meeting transcripts and summary to a Markdown file.
///
/// Shows a save dialog, then writes a formatted .md file containing:
/// - Meeting title and metadata
/// - Full transcript with timestamps
/// - AI summary (if available)
///
/// # Arguments
/// * `meeting_id` - The meeting to export
///
/// # Returns
/// File path and success status
#[tauri::command]
pub async fn api_export_meeting_markdown<R: tauri::Runtime>(
    app: tauri::AppHandle<R>,
    state: tauri::State<'_, AppState>,
    meeting_id: String,
) -> Result<ExportMarkdownResponse, String> {
    log_info!(
        "Exporting meeting {} to Markdown",
        meeting_id
    );

    let pool = &state.db_manager.pool;

    // 1. Get meeting details
    let meeting = MeetingsRepository::get_meeting(pool, &meeting_id)
        .await
        .map_err(|e| format!("Failed to fetch meeting: {}", e))?
        .ok_or_else(|| format!("Meeting {} not found", meeting_id))?;

    // 2. Get all transcripts
    let (transcripts, _) =
        MeetingsRepository::get_meeting_transcripts_paginated(pool, &meeting_id, 10000, 0)
            .await
            .map_err(|e| format!("Failed to fetch transcripts: {}", e))?;

    // 3. Get summary if available
    let summary_markdown: Option<String> = sqlx::query_scalar(
        "SELECT markdown FROM summary_processes WHERE meeting_id = ? ORDER BY created_at DESC LIMIT 1",
    )
    .bind(&meeting_id)
    .fetch_optional(pool)
    .await
    .map_err(|e| format!("Failed to fetch summary: {}", e))?;

    // 4. Build markdown content
    let mut md = String::new();

    // Header
    md.push_str(&format!("# {}\n\n", meeting.title));

    // Metadata
    md.push_str("## Meeting Info\n\n");
    md.push_str(&format!("- **Date:** {}\n", meeting.created_at.format("%Y-%m-%d %H:%M")));
    md.push_str(&format!("- **Meeting ID:** `{}`\n", meeting.id));
    md.push_str(&format!(
        "- **Exported:** {}\n",
        chrono::Utc::now().format("%Y-%m-%d %H:%M UTC")
    ));
    md.push('\n');

    // Transcripts
    if !transcripts.is_empty() {
        md.push_str("## Transcript\n\n");
        for segment in &transcripts {
            // Format timestamps as MM:SS
            let timestamp_str = segment
                .audio_start_time
                .map(|t| {
                    let total_secs = t as u64;
                    format!(
                        "[{:02}:{:02}]",
                        total_secs / 60,
                        total_secs % 60
                    )
                })
                .unwrap_or_else(|| format!("[{}]", &segment.timestamp[..19.min(segment.timestamp.len())]));

            md.push_str(&format!("{} {}\n\n", timestamp_str, segment.transcript));
        }
    } else {
        md.push_str("## Transcript\n\n_No transcript data available._\n\n");
    }

    // Summary
    if let Some(summary) = summary_markdown {
        md.push_str("---\n\n## AI Summary\n\n");
        md.push_str(&summary);
        md.push('\n');
    }

    // Footer
    md.push_str("\n---\n_Generated by [Meetily](https://github.com/Zackriya-Solutions/meetily)_\n");

    // 5. Show save dialog
    let file_path = app
        .dialog()
        .file()
        .add_filter("Markdown", &["md"])
        .set_file_name(&format!(
            "{}.md",
            meeting
                .title
                .chars()
                .map(|c| if c.is_alphanumeric() || c == ' ' || c == '-' || c == '_' {
                    c
                } else {
                    '_'
                })
                .collect::<String>()
                .trim()
                .replace(' ', "_")
        ))
        .blocking_save_file();

    let file_path = match file_path {
        Some(path) => path.to_string(),
        None => {
            log_info!("User cancelled export dialog");
            return Err("User cancelled export".to_string());
        }
    };

    // 6. Write file
    std::fs::write(&file_path, &md).map_err(|e| {
        let msg = format!("Failed to write file: {}", e);
        log_error!("{}", msg);
        msg
    })?;

    let bytes_written = md.len() as u64;
    log_info!(
        "Exported meeting {} to {} ({} bytes)",
        meeting_id,
        file_path,
        bytes_written
    );

    Ok(ExportMarkdownResponse {
        file_path,
        success: true,
        bytes_written,
    })
}

/// Export meeting summary only (without full transcript) to clipboard-friendly markdown.
///
/// Useful for quick sharing — returns the markdown string directly
/// instead of saving to a file.
#[tauri::command]
pub async fn api_get_meeting_markdown(
    state: tauri::State<'_, AppState>,
    meeting_id: String,
) -> Result<String, String> {
    let pool = &state.db_manager.pool;

    let meeting = MeetingsRepository::get_meeting(pool, &meeting_id)
        .await
        .map_err(|e| format!("Failed to fetch meeting: {}", e))?
        .ok_or_else(|| format!("Meeting {} not found", meeting_id))?;

    let (transcripts, _) =
        MeetingsRepository::get_meeting_transcripts_paginated(pool, &meeting_id, 10000, 0)
            .await
            .map_err(|e| format!("Failed to fetch transcripts: {}", e))?;

    let summary_markdown: Option<String> = sqlx::query_scalar(
        "SELECT markdown FROM summary_processes WHERE meeting_id = ? ORDER BY created_at DESC LIMIT 1",
    )
    .bind(&meeting_id)
    .fetch_optional(pool)
    .await
    .map_err(|e| format!("Failed to fetch summary: {}", e))?;

    let mut md = String::new();
    md.push_str(&format!("# {}\n\n", meeting.title));
    md.push_str(&format!(
        "- **Date:** {}\n",
        meeting.created_at.format("%Y-%m-%d %H:%M")
    ));
    md.push('\n');

    if !transcripts.is_empty() {
        md.push_str("## Transcript\n\n");
        for segment in &transcripts {
            let ts = segment
                .audio_start_time
                .map(|t| {
                    let s = t as u64;
                    format!("[{:02}:{:02}]", s / 60, s % 60)
                })
                .unwrap_or_default();
            md.push_str(&format!("{} {}\n\n", ts, segment.transcript));
        }
    }

    if let Some(summary) = summary_markdown {
        md.push_str("---\n\n## Summary\n\n");
        md.push_str(&summary);
    }

    Ok(md)
}
