import type { ComponentType, SVGProps } from 'react';
import { Icon, type MementoIconName } from './Icon';

type CompatProps = SVGProps<SVGSVGElement> & { size?: number | string; absoluteStrokeWidth?: boolean };

function makeIcon(name: MementoIconName): ComponentType<CompatProps> {
  function MementoCompatIcon({ size = 20, absoluteStrokeWidth: _absoluteStrokeWidth, ...props }: CompatProps) {
    const numericSize = typeof size === 'number' ? size : Number.parseFloat(size) || 20;
    return <Icon {...props} name={name} size={numericSize} />;
  }
  MementoCompatIcon.displayName = `MementoIcon(${name})`;
  return MementoCompatIcon;
}

export const AlertCircle = makeIcon('alert');
export const AlertTriangle = makeIcon('alert');
export const ArrowBigDownDash = makeIcon('download');
export const BadgeAlert = makeIcon('alert');
export const BrainCircuit = makeIcon('spark');
export const Calendar = makeIcon('calendar');
export const Check = makeIcon('check');
export const CheckCircle = makeIcon('check-circle');
export const CheckCircle2 = makeIcon('check-circle');
export const ChevronDown = makeIcon('chevron-down');
export const ChevronDownIcon = makeIcon('chevron-down');
export const ChevronLeftCircle = makeIcon('back');
export const ChevronRight = makeIcon('chevron-right');
export const ChevronRightCircle = makeIcon('chevron-right');
export const ChevronUp = makeIcon('chevron-up');
export const ChevronsUpDown = makeIcon('filter');
export const Circle = makeIcon('circle');
export const Clock = makeIcon('clock');
export const Copy = makeIcon('copy');
export const Cpu = makeIcon('database');
export const Database = makeIcon('database');
export const Download = makeIcon('download');
export const ExternalLink = makeIcon('external');
export const Eye = makeIcon('eye');
export const EyeOff = makeIcon('eye-off');
export const File = makeIcon('transcript');
export const FileAudio = makeIcon('wave');
export const FileQuestion = makeIcon('transcript');
export const FileText = makeIcon('transcript');
export const FlaskConical = makeIcon('spark');
export const FolderOpen = makeIcon('folder');
export const Globe = makeIcon('globe');
export const GlobeIcon = makeIcon('globe');
export const HardDrive = makeIcon('database');
export const Home = makeIcon('home');
export const Info = makeIcon('info');
export const KeyRound = makeIcon('lock');
export const Languages = makeIcon('globe');
export const Loader2 = makeIcon('loader');
export const LoaderIcon = makeIcon('loader');
export const Lock = makeIcon('lock');
export const MessageSquare = makeIcon('chat');
export const Mic = makeIcon('mic');
export const NotebookPen = makeIcon('transcript');
export const Pause = makeIcon('pause');
export const Pencil = makeIcon('edit');
export const Pin = makeIcon('pin');
export const Play = makeIcon('play');
export const Plus = makeIcon('plus');
export const RefreshCw = makeIcon('refresh');
export const RotateCw = makeIcon('refresh');
export const Save = makeIcon('save');
export const Search = makeIcon('search');
export const SearchIcon = makeIcon('search');
export const Settings = makeIcon('settings');
export const Shield = makeIcon('lock');
export const Sparkles = makeIcon('spark');
export const Speaker = makeIcon('speaker');
export const Square = makeIcon('stop');
export const StickyNote = makeIcon('transcript');
export const Tag = makeIcon('tag');
export const Trash2 = makeIcon('trash');
export const Unlock = makeIcon('unlock');
export const Upload = makeIcon('upload');
export const Users = makeIcon('users');
export const X = makeIcon('close');
export const XCircle = makeIcon('close-circle');
