//! The example meeting a fresh install starts with.
//!
//! Until a first real recording exists, every screen in the app is empty: there is no
//! transcript to read, no summary to judge, and no analytical report to open. So a fresh
//! database gets one synthetic meeting — a short fictional planning call — with the same
//! artifacts a real recording would have: a diarized transcript on a real timeline, a
//! completed summary, and a completed analytics report (row + rendered HTML).
//!
//! Nothing here calls an LLM. The conversation and the stage artifacts are authored
//! constants; the two things that must not drift from real runs — `Dynamics` and the
//! meeting score — are computed by the pipeline's own deterministic code over the seeded
//! transcript, and the HTML comes from the pipeline's own renderer.
//!
//! Seeding happens once. The marker in `app_settings_kv` is written after a successful
//! seed, so deleting the example is permanent: it never comes back on the next launch.

use serde_json::json;
use sqlx::SqlitePool;
use tauri::{AppHandle, Runtime};

use crate::report::dynamics::{self, Dynamics};
use crate::report::prompts::{
    AgendaItem, Classification, Commitment, Commitments, Decision, Decisions, Disagreement,
    DisagreementsConcepts, Insight, Insights, NumberItem, Numbers, OpenThread, Participant,
    Position, Risk, Role, Roles, ThreadsRisks, Topic, Topics,
};
use crate::report::render::{compute_score, render_report, RenderInput};

/// Set once the example has been seeded. Its presence — not the meeting's — is what stops
/// re-seeding, so a user who deletes the example keeps it deleted.
const MARKER_KEY: &str = "demo.meeting.seeded";

/// Fixed id: the frontend opens this meeting right after onboarding, and a stable id keeps
/// that link valid without a round-trip to find it.
pub const DEMO_MEETING_ID: &str = "meeting-example-memento";

const TITLE: &str = "Пример: планёрка по релизу «Компаса»";

/// Model recorded on the example report row. It was not generated by a model, and saying so
/// is better than attributing authored text to DeepSeek.
const REPORT_MODEL: &str = "пример (без обращения к модели)";

/// One reply: start second, speaker index into [`SPEAKER_NAMES`], text.
struct Reply(f64, usize, &'static str);

const SPEAKER_NAMES: [&str; 3] = ["Аня", "Игорь", "Марина"];

/// A fictional six-minute release planning call. Deliberately imperfect: one agenda item is
/// only half-covered, one disagreement is parked, and one thread is left open — so the
/// report's score and «Что мешало» have something true to say.
const REPLIES: &[Reply] = &[
    Reply(0.0, 0, "Привет, всех вижу. План такой: сроки релиза, отвал на онбординге и что делаем с оплатой. Пятнадцать минут, не больше."),
    Reply(12.0, 1, "Привет. По срокам: бэкенд для версии два четыре готов, тесты зелёные с четверга."),
    Reply(21.0, 2, "Я ещё дорисовываю оплату. Два экрана из пяти готовы."),
    Reply(29.0, 0, "Что мешает закрыть остальные три?"),
    Reply(33.0, 2, "Нужны финальные тексты. Я отправила запрос вчера, ответа пока нет."),
    Reply(42.0, 0, "Тексты на мне, пришлю до конца дня. Тогда фиксируем: релиз в пятницу, двадцать первого."),
    Reply(54.0, 1, "Если тексты будут сегодня, я успею собрать сборку в четверг утром."),
    Reply(64.0, 0, "Договорились. Игорь, ты собираешь сборку в четверг до двенадцати и выкладываешь в TestFlight."),
    Reply(74.0, 1, "Принял. Четверг, до двенадцати."),
    Reply(80.0, 0, "Теперь отвал. Марина, покажи цифры."),
    Reply(86.0, 2, "На третьем шаге онбординга уходит двенадцать целых четыре десятых процента. Это примерно каждый восьмой."),
    Reply(99.0, 0, "А было сколько?"),
    Reply(103.0, 2, "Восемь процентов месяц назад. Выросло после того, как мы добавили экран с разрешениями."),
    Reply(115.0, 1, "Тогда причина понятна: мы просим доступ к микрофону раньше, чем человек понимает, зачем он нужен."),
    Reply(128.0, 2, "Я предлагаю показывать один пример результата до запроса разрешений. Не текстом, а готовой карточкой встречи."),
    Reply(142.0, 0, "Нравится. Это дешевле, чем переделывать весь онбординг."),
    Reply(150.0, 1, "Дешевле, но не бесплатно: карточку нужно откуда-то взять. Я бы зашил её в приложение."),
    Reply(162.0, 2, "Тогда я нарисую её вместе с экранами оплаты, до среды."),
    Reply(170.0, 0, "Фиксируем: Марина — три экрана оплаты и карточка-пример до среды. Готово — это когда макеты в Figma и я их посмотрела."),
    Reply(186.0, 2, "Да, так и запишем."),
    Reply(191.0, 0, "Осталась оплата. Игорь, ты в прошлый раз был против того, чтобы отдавать её в этот релиз."),
    Reply(202.0, 1, "И остаюсь против. У нас нет ни одного теста на возвраты. Если что-то отвалится, мы узнаем об этом от пользователей."),
    Reply(216.0, 2, "Но без оплаты релиз выглядит незаконченным. Мы обещали её в двух письмах."),
    Reply(226.0, 1, "Обещали. Я просто не хочу, чтобы первое, что увидит человек, — это списание без доступа."),
    Reply(238.0, 0, "Хорошо. Давайте так: решение по оплате не принимаем сейчас. Игорь оценивает тесты на возвраты, и в среду решаем на цифрах."),
    Reply(254.0, 1, "Оценю. Ощущение — три дня работы, но проверю."),
    Reply(266.0, 0, "Промокоды в этом релизе трогаем?"),
    Reply(271.0, 2, "Я бы не трогала."),
    Reply(275.0, 1, "У меня нет мнения. Их всё равно некому тестировать."),
    Reply(281.0, 0, "Тогда оставляем открытым, вернёмся после релиза."),
    Reply(292.0, 0, "И последнее: бюджет на аналитику. Сорок тысяч в месяц, я согласовала."),
    Reply(303.0, 1, "Этого хватит, если не включать запись сессий."),
    Reply(312.0, 0, "Не включаем. Всё, спасибо. Итог: релиз в пятницу, оплата — решаем в среду, промокоды — после релиза."),
    Reply(330.0, 2, "Спасибо."),
    Reply(333.0, 1, "Пока."),
];

fn already_seeded(pool: &SqlitePool) -> impl std::future::Future<Output = bool> + '_ {
    async move {
        sqlx::query_scalar::<_, String>("SELECT value FROM app_settings_kv WHERE key = ? LIMIT 1")
            .bind(MARKER_KEY)
            .fetch_optional(pool)
            .await
            .ok()
            .flatten()
            .is_some()
    }
}

/// Insert the example meeting, its transcript, summary and analytics report.
///
/// Returns the meeting id when something was seeded, `None` when the example already
/// exists (or was deliberately deleted). A failure is logged and swallowed by callers: the
/// example is a convenience, never a precondition for using the app.
pub async fn seed<R: Runtime>(
    app: &AppHandle<R>,
    pool: &SqlitePool,
) -> Result<Option<String>, String> {
    if already_seeded(pool).await {
        return Ok(None);
    }

    let date_str = seed_meeting(pool).await?;

    if let Err(error) = seed_report(app, pool, &date_str).await {
        // The transcript and the summary are already in place; a meeting without the
        // analytics section is still a useful example.
        log::warn!("[demo] example report not created: {error}");
    }

    sqlx::query(
        "INSERT OR REPLACE INTO app_settings_kv (key, value, updated_at) \
         VALUES (?, 'true', datetime('now'))",
    )
    .bind(MARKER_KEY)
    .execute(pool)
    .await
    .map_err(|e| format!("не удалось отметить пример как созданный: {e}"))?;

    log::info!("[demo] seeded the example meeting {DEMO_MEETING_ID}");
    Ok(Some(DEMO_MEETING_ID.to_string()))
}

/// The database half: meeting, speakers, transcript, summary. Returns the meeting's date for
/// the report header. Separate from [`seed`] so it can be tested against a migrated schema
/// without a Tauri app handle.
async fn seed_meeting(pool: &SqlitePool) -> Result<String, String> {
    let now = chrono::Utc::now();
    let started = now - chrono::Duration::minutes(20);

    let mut tx = pool
        .begin()
        .await
        .map_err(|e| format!("не удалось открыть транзакцию для примера встречи: {e}"))?;

    sqlx::query(
        "INSERT OR REPLACE INTO meetings (id, title, created_at, updated_at) VALUES (?, ?, ?, ?)",
    )
    .bind(DEMO_MEETING_ID)
    .bind(TITLE)
    .bind(started)
    .bind(now)
    .execute(&mut *tx)
    .await
    .map_err(|e| format!("не удалось создать пример встречи: {e}"))?;

    // Confirmed speakers: the example shows named people, not "Спикер 1". No voice
    // embedding is stored — these names must never take part in matching a real voice.
    let mut speaker_ids = Vec::with_capacity(SPEAKER_NAMES.len());
    for name in SPEAKER_NAMES {
        let result = sqlx::query(
            "INSERT INTO speakers (display_name, is_confirmed, created_at) \
             VALUES (?, 1, datetime('now'))",
        )
        .bind(name)
        .execute(&mut *tx)
        .await
        .map_err(|e| format!("не удалось создать участника примера: {e}"))?;
        speaker_ids.push(result.last_insert_rowid());
    }

    for (index, Reply(at, speaker, text)) in REPLIES.iter().enumerate() {
        // The spoken end is what the pipeline estimates from the text, bounded by the next
        // reply; storing the same bound keeps per-speaker speech time honest in the UI.
        let next_start = REPLIES.get(index + 1).map(|Reply(next, _, _)| *next);
        let estimated_end = at + (text.split_whitespace().count() as f64 / 2.5).max(0.5);
        let end = next_start.map_or(estimated_end, |next| estimated_end.min(next));

        sqlx::query(
            "INSERT INTO transcripts \
             (id, meeting_id, transcript, timestamp, audio_start_time, audio_end_time, duration, speaker_id) \
             VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
        )
        .bind(format!("transcript-example-{index:03}"))
        .bind(DEMO_MEETING_ID)
        .bind(*text)
        .bind((started + chrono::Duration::milliseconds((at * 1000.0) as i64)).to_rfc3339())
        .bind(*at)
        .bind(end)
        .bind(end - at)
        .bind(speaker_ids[*speaker])
        .execute(&mut *tx)
        .await
        .map_err(|e| format!("не удалось сохранить реплику примера: {e}"))?;
    }

    sqlx::query(
        "INSERT OR REPLACE INTO summary_processes \
         (meeting_id, status, created_at, updated_at, start_time, end_time, result, chunk_count, processing_time) \
         VALUES (?, 'completed', ?, ?, ?, ?, ?, 1, 0)",
    )
    .bind(DEMO_MEETING_ID)
    .bind(now)
    .bind(now)
    .bind(now)
    .bind(now)
    .bind(json!({ "markdown": SUMMARY_MARKDOWN }).to_string())
    .execute(&mut *tx)
    .await
    .map_err(|e| format!("не удалось сохранить итоги примера: {e}"))?;

    tx.commit()
        .await
        .map_err(|e| format!("не удалось сохранить пример встречи: {e}"))?;

    Ok(started.format("%d.%m.%Y").to_string())
}

/// Build the analytics report for the example: authored stage artifacts, deterministic
/// dynamics and score, and the real HTML renderer. Returns the artifacts snapshot the meeting
/// screen reads and the rendered HTML.
async fn build_report(pool: &SqlitePool, date_str: &str) -> Result<(String, String), String> {
    use crate::database::repositories::speaker::SpeakersRepository;

    let segments = SpeakersRepository::meeting_transcript_segments(pool, DEMO_MEETING_ID)
        .await
        .map_err(|e| format!("не удалось прочитать расшифровку примера: {e}"))?;
    let (dyn_segments, seg_labels, seg_texts) =
        crate::report::pipeline::build_segment_views(&segments);
    let timed = dynamics::timeline(&dyn_segments);
    let metrics = Dynamics::from_timed(&dyn_segments, &timed);

    let classification = classification();
    let topics = topics();
    let decisions = decisions();
    let commitments = commitments();
    let threads_risks = threads_risks();
    let disagreements = disagreements_concepts();
    let numbers = numbers();
    let roles = roles();
    let insights = insights();
    let score = compute_score(
        &topics.agenda,
        &commitments.commitments,
        threads_risks.open_threads.len(),
    );

    let html = render_report(&RenderInput {
        meeting_title: TITLE,
        date_str,
        model: REPORT_MODEL,
        generation_secs: 0.0,
        total_stages: crate::database::repositories::analytics_report::TOTAL_STAGES,
        dynamics: &metrics,
        timed: &timed,
        seg_labels: &seg_labels,
        seg_texts: &seg_texts,
        classification: Some(&classification),
        topics: Some(&topics),
        decisions: Some(&decisions),
        commitments: Some(&commitments),
        threads_risks: Some(&threads_risks),
        disagreements_concepts: Some(&disagreements),
        numbers: Some(&numbers),
        roles: Some(&roles),
        insights: Some(&insights),
        score: &score,
        clarify_questions: &[],
        clarify_answers: &[],
    });

    let artifacts = json!({
        "segment_count": seg_texts.len(),
        "dynamics": metrics,
        "score": score,
        "classification": classification,
        "clarify_questions": [],
        "clarify_answers": [],
        "topics": topics,
        "decisions": decisions,
        "commitments": commitments,
        "threads_risks": threads_risks,
        "disagreements_concepts": disagreements,
        "numbers": numbers,
        "roles": roles,
        "insights": insights,
        "failed_stages": [],
    })
    .to_string();

    Ok((artifacts, html))
}

/// Persist the example's report: write the HTML the «Открыть отчёт» action opens, then record
/// a completed run pointing at it.
async fn seed_report<R: Runtime>(
    app: &AppHandle<R>,
    pool: &SqlitePool,
    date_str: &str,
) -> Result<(), String> {
    use crate::database::repositories::analytics_report::AnalyticsReportsRepository;

    let (artifacts, html) = build_report(pool, date_str).await?;
    let html_path = crate::report::pipeline::write_html(app, DEMO_MEETING_ID, None, &html)?;

    let report_id = format!("report-example-{DEMO_MEETING_ID}");
    AnalyticsReportsRepository::insert(pool, &report_id, DEMO_MEETING_ID, REPORT_MODEL)
        .await
        .map_err(|e| format!("не удалось создать строку отчёта примера: {e}"))?;
    AnalyticsReportsRepository::mark_completed(pool, &report_id, &html_path, &artifacts)
        .await
        .map_err(|e| format!("не удалось завершить отчёт примера: {e}"))?;

    Ok(())
}

const SUMMARY_MARKDOWN: &str = r#"## О чём договорились

- **Релиз 2.4 — в пятницу, 21-го.** Бэкенд готов, тесты зелёные с четверга.
- **Оплату в этот релиз не отдаём — решаем в среду.** Игорь оценивает тесты на возвраты, решение принимается на его цифрах.
- **Промокоды остаются за рамками релиза**, вернёмся к ним после.

## Задачи

- **Аня** — финальные тексты для экранов оплаты, до конца дня.
- **Игорь** — сборка в четверг до 12:00, выложить в TestFlight. Отдельно: оценить тесты на возвраты к среде.
- **Марина** — три оставшихся экрана оплаты и карточка-пример для онбординга, до среды. Готово = макеты в Figma и Аня их посмотрела.

## Отвал на онбординге

Третий шаг теряет **12,4 %** — месяц назад было 8 %. Рост начался после экрана с разрешениями: доступ к микрофону запрашивается раньше, чем человек понимает, зачем он нужен.

Договорились показывать один пример результата до запроса разрешений — готовой карточкой встречи, зашитой в приложение.

## Осталось открытым

- Промокоды: решения нет, ответственного нет.
- Тестов на возвраты нет ни одного — до среды это открытый риск.
"#;

fn classification() -> Classification {
    Classification {
        meeting_type: "Планирование релиза".to_string(),
        confidence: 0.9,
        title: TITLE.to_string(),
        participants: vec![
            Participant {
                speaker: "Аня".to_string(),
                role_hint: "продакт-менеджер, ведёт встречу".to_string(),
            },
            Participant {
                speaker: "Игорь".to_string(),
                role_hint: "бэкенд-разработчик".to_string(),
            },
            Participant {
                speaker: "Марина".to_string(),
                role_hint: "дизайнер".to_string(),
            },
        ],
    }
}

fn topics() -> Topics {
    Topics {
        topics: vec![
            Topic {
                name: "Сроки релиза 2.4".to_string(),
                start_s: 0.0,
                end_s: 80.0,
            },
            Topic {
                name: "Отвал на онбординге".to_string(),
                start_s: 80.0,
                end_s: 191.0,
            },
            Topic {
                name: "Оплата и промокоды".to_string(),
                start_s: 191.0,
                end_s: 292.0,
            },
            Topic {
                name: "Бюджет на аналитику".to_string(),
                start_s: 292.0,
                end_s: 336.0,
            },
        ],
        agenda: vec![
            AgendaItem {
                item: "Сроки релиза".to_string(),
                status: "covered".to_string(),
                seg: 5,
            },
            AgendaItem {
                item: "Отвал на онбординге".to_string(),
                status: "covered".to_string(),
                seg: 10,
            },
            AgendaItem {
                item: "Что делаем с оплатой".to_string(),
                status: "partial".to_string(),
                seg: 24,
            },
        ],
    }
}

fn decisions() -> Decisions {
    Decisions {
        decisions: vec![
            Decision {
                statement: "Релиз 2.4 выходит в пятницу, 21-го".to_string(),
                rationale: Some("бэкенд готов, тесты зелёные с четверга".to_string()),
                quality_badges: vec!["есть дата".to_string(), "есть владелец".to_string()],
                seg: 5,
            },
            Decision {
                statement: "Показывать пример результата до запроса разрешений в онбординге"
                    .to_string(),
                rationale: Some(
                    "дешевле, чем переделывать онбординг целиком; причина отвала — ранний запрос доступа"
                        .to_string(),
                ),
                quality_badges: vec!["есть владелец".to_string()],
                seg: 14,
            },
            Decision {
                statement: "Промокоды в релиз 2.4 не входят".to_string(),
                rationale: Some("их некому тестировать".to_string()),
                quality_badges: vec![],
                seg: 29,
            },
        ],
    }
}

fn commitments() -> Commitments {
    Commitments {
        commitments: vec![
            Commitment {
                who: "Аня".to_string(),
                what: "прислать финальные тексты для экранов оплаты".to_string(),
                due: Some("до конца дня".to_string()),
                quote: "Тексты на мне, пришлю до конца дня.".to_string(),
                seg: 5,
                hedge: "firm".to_string(),
                has_owner: true,
                has_dod: false,
                dod_note: None,
            },
            Commitment {
                who: "Игорь".to_string(),
                what: "собрать сборку и выложить в TestFlight".to_string(),
                due: Some("четверг, до 12:00".to_string()),
                quote: "Принял. Четверг, до двенадцати.".to_string(),
                seg: 7,
                hedge: "firm".to_string(),
                has_owner: true,
                has_dod: true,
                dod_note: Some("сборка доступна в TestFlight".to_string()),
            },
            Commitment {
                who: "Марина".to_string(),
                what: "три экрана оплаты и карточка-пример для онбординга".to_string(),
                due: Some("среда".to_string()),
                quote: "Тогда я нарисую её вместе с экранами оплаты, до среды.".to_string(),
                seg: 18,
                hedge: "firm".to_string(),
                has_owner: true,
                has_dod: true,
                dod_note: Some("макеты в Figma, Аня их посмотрела".to_string()),
            },
            Commitment {
                who: "Игорь".to_string(),
                what: "оценить объём тестов на возвраты".to_string(),
                due: Some("к среде".to_string()),
                quote: "Оценю. Ощущение — три дня работы, но проверю.".to_string(),
                seg: 25,
                hedge: "hedged".to_string(),
                has_owner: true,
                has_dod: false,
                dod_note: None,
            },
        ],
    }
}

fn threads_risks() -> ThreadsRisks {
    ThreadsRisks {
        open_threads: vec![
            OpenThread {
                text: "Промокоды: решения нет, ответственного нет — «вернёмся после релиза»"
                    .to_string(),
                seg: 29,
                severity: "info".to_string(),
            },
            OpenThread {
                text: "Судьба оплаты в релизе 2.4 не решена — перенесено на среду".to_string(),
                seg: 24,
                severity: "warn".to_string(),
            },
        ],
        risks: vec![
            Risk {
                text:
                    "Нет ни одного теста на возвраты: ошибку в оплате первыми найдут пользователи"
                        .to_string(),
                severity: "serious".to_string(),
                seg: 21,
            },
            Risk {
                text: "Релиз в пятницу зависит от текстов, которых на момент встречи ещё нет"
                    .to_string(),
                severity: "warn".to_string(),
                seg: 4,
            },
        ],
    }
}

fn disagreements_concepts() -> DisagreementsConcepts {
    DisagreementsConcepts {
        disagreements: vec![Disagreement {
            topic: "Отдавать ли оплату в релиз 2.4".to_string(),
            positions: vec![
                Position {
                    who: "Игорь".to_string(),
                    stance: "против: нет тестов на возвраты, риск списания без доступа".to_string(),
                    seg: 21,
                },
                Position {
                    who: "Марина".to_string(),
                    stance: "за: без оплаты релиз выглядит незаконченным, её обещали в письмах"
                        .to_string(),
                    seg: 22,
                },
            ],
            resolution: "Решение отложено до среды: Игорь приносит оценку тестов, решаем на цифрах"
                .to_string(),
            resolved: false,
        }],
        concepts: vec![],
    }
}

fn numbers() -> Numbers {
    Numbers {
        numbers: vec![
            NumberItem {
                metric: "Отвал на третьем шаге онбординга".to_string(),
                value: "12,4 %".to_string(),
                seg: 10,
                check: "было 8 % месяц назад — рост в 1,5 раза".to_string(),
                status: "warn".to_string(),
            },
            NumberItem {
                metric: "Экраны оплаты готовы".to_string(),
                value: "2 из 5".to_string(),
                seg: 2,
                check: "остальные три ждут финальных текстов".to_string(),
                status: "info".to_string(),
            },
            NumberItem {
                metric: "Оценка тестов на возвраты".to_string(),
                value: "≈ 3 дня".to_string(),
                seg: 25,
                check: "оценка «по ощущению», подтверждается к среде".to_string(),
                status: "warn".to_string(),
            },
            NumberItem {
                metric: "Бюджет на аналитику".to_string(),
                value: "40 000 ₽ / месяц".to_string(),
                seg: 30,
                check: "согласован; хватает без записи сессий".to_string(),
                status: "ok".to_string(),
            },
        ],
    }
}

fn roles() -> Roles {
    Roles {
        roles: vec![
            Role {
                speaker: "Аня".to_string(),
                role: "Ведёт и фиксирует".to_string(),
                evidence: "задаёт повестку, формулирует решения и критерии готовности".to_string(),
                seg: 18,
            },
            Role {
                speaker: "Игорь".to_string(),
                role: "Держит риски".to_string(),
                evidence: "возражает против оплаты без тестов на возвраты".to_string(),
                seg: 21,
            },
            Role {
                speaker: "Марина".to_string(),
                role: "Приносит данные и решение".to_string(),
                evidence: "показывает цифры отвала и предлагает пример до запроса разрешений"
                    .to_string(),
                seg: 14,
            },
        ],
    }
}

fn insights() -> Insights {
    Insights {
        insights: vec![
            Insight {
                title: "Одно из трёх решений держится на обещании, а не на дате".to_string(),
                body: "Релиз в пятницу зависит от текстов, которых на встрече ещё нет. Владелец назван, дата названа, но проверить исполнение можно только в четверг утром — когда переносить будет поздно.".to_string(),
                severity: "warn".to_string(),
                category: "исполнимость".to_string(),
                segs: vec![4, 5, 6],
            },
            Insight {
                title: "Отвал вырос после изменения, которое никто не откатил".to_string(),
                body: "Экран разрешений добавили месяц назад, отвал вырос с 8 % до 12,4 %. Встреча приняла надстройку сверху (пример до разрешений), но не обсудила, нужен ли этот экран на прежнем месте.".to_string(),
                severity: "serious".to_string(),
                category: "продукт".to_string(),
                segs: vec![12, 13, 14],
            },
            Insight {
                title: "Разногласие по оплате разрешено процедурой, а не аргументом".to_string(),
                body: "Обе позиции остались при себе; решение перенесено на цифры Игоря. Это честный ход, но он требует, чтобы оценка действительно появилась к среде — иначе спор вернётся в тот же вид.".to_string(),
                severity: "info".to_string(),
                category: "процесс".to_string(),
                segs: vec![21, 22, 24],
            },
        ],
        verdict: "Встреча закрыла сроки и нашла причину отвала, но оставила оплату и промокоды без решения.".to_string(),
        what_hindered: vec![
            "Финальных текстов не было на руках — три экрана оплаты нельзя было закрыть.".to_string(),
            "Нет тестов на возвраты, поэтому спор об оплате нечем было разрешить на встрече.".to_string(),
            "Промокоды обсудили тремя репликами и оставили без ответственного.".to_string(),
        ],
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use sqlx::sqlite::SqlitePoolOptions;

    async fn migrated_pool() -> SqlitePool {
        let pool = SqlitePoolOptions::new()
            .max_connections(1)
            .connect("sqlite::memory:")
            .await
            .unwrap();
        sqlx::migrate!("./migrations").run(&pool).await.unwrap();
        pool
    }

    /// The example is only useful if the app can read it back. This walks the same path the
    /// meeting screen takes — transcript segments, the deterministic timeline, then
    /// `sections::build` over the stored snapshot — so a wrong column, a NOT NULL violation,
    /// or an artifact shape the reader rejects fails here rather than on a user's first launch.
    #[tokio::test]
    async fn the_example_is_readable_by_the_meeting_screen() {
        use crate::database::repositories::speaker::SpeakersRepository;
        use crate::report::sections::{self, TranscriptTimeline};

        let pool = migrated_pool().await;
        seed_meeting(&pool).await.expect("example seeds");

        let segments = SpeakersRepository::meeting_transcript_segments(&pool, DEMO_MEETING_ID)
            .await
            .expect("transcript reads back");
        assert_eq!(segments.len(), REPLIES.len());
        assert!(
            segments.iter().all(|s| s.display_name.is_some()),
            "every reply must carry a speaker name, not «Спикер 1»"
        );

        let summary = sqlx::query_scalar::<_, String>(
            "SELECT result FROM summary_processes WHERE meeting_id = ? AND status = 'completed'",
        )
        .bind(DEMO_MEETING_ID)
        .fetch_one(&pool)
        .await
        .expect("summary is stored as a completed process");
        assert!(
            summary.contains("markdown"),
            "summary must be in the markdown format the UI reads"
        );

        let (artifacts, html) = build_report(&pool, "06.08.2026")
            .await
            .expect("report builds");
        assert!(
            html.contains("Компас"),
            "the rendered report mentions the meeting"
        );

        let (dyn_segments, _, texts) = crate::report::pipeline::build_segment_views(&segments);
        let timed = dynamics::timeline(&dyn_segments);
        let live = Dynamics::from_timed(&dyn_segments, &timed);
        let built = sections::build(
            "report-example",
            Some("2026-08-06 10:00:00".to_string()),
            &artifacts,
            Some(&TranscriptTimeline {
                timed: &timed,
                texts: &texts,
                dynamics: &live,
            }),
        )
        .expect("the snapshot parses");

        let score = built.score.expect("the score section is present");
        assert!(score.total > 0 && !score.verdict.is_empty());
        assert_eq!(built.agenda.len(), 3, "all three agenda items are shown");
        assert_eq!(built.numbers.len(), 4);
        assert_eq!(built.roles.len(), 3);
        assert!(!built.what_hindered.is_empty());

        // Provenance: `segment_count` matches, so every moment link must resolve. A silently
        // dropped link is exactly the failure this snapshot exists to avoid.
        assert!(
            built.agenda.iter().all(|item| item.at_seconds.is_some()),
            "agenda moments must resolve against the seeded transcript"
        );
        assert!(built.numbers.iter().all(|row| row.at_seconds.is_some()));

        let dynamics_section = built.dynamics.expect("dynamics are present");
        assert_eq!(dynamics_section.speakers.len(), SPEAKER_NAMES.len());
        assert_eq!(dynamics_section.decisions_count, Some(3));
        assert_eq!(dynamics_section.commitments_count, Some(4));

        let timeline = built.timeline.expect("the feed is present");
        assert_eq!(timeline.turns.len(), REPLIES.len());
        assert!(!timeline.topics.is_empty());
        assert!(
            timeline.markers.len() >= 7,
            "decisions, commitments and the disagreement all mark the feed"
        );
    }

    #[test]
    fn every_referenced_segment_exists() {
        let last = (REPLIES.len() - 1) as i64;
        let mut segs: Vec<i64> = Vec::new();
        segs.extend(topics().agenda.iter().map(|a| a.seg));
        segs.extend(decisions().decisions.iter().map(|d| d.seg));
        segs.extend(commitments().commitments.iter().map(|c| c.seg));
        segs.extend(threads_risks().open_threads.iter().map(|t| t.seg));
        segs.extend(threads_risks().risks.iter().map(|r| r.seg));
        segs.extend(numbers().numbers.iter().map(|n| n.seg));
        segs.extend(roles().roles.iter().map(|r| r.seg));
        segs.extend(insights().insights.iter().flat_map(|i| i.segs.clone()));
        segs.extend(
            disagreements_concepts()
                .disagreements
                .iter()
                .flat_map(|d| d.positions.iter().map(|p| p.seg)),
        );

        for seg in segs {
            assert!(
                (0..=last).contains(&seg),
                "artifact points at reply {seg}, which the example transcript does not have"
            );
        }
    }

    #[test]
    fn replies_are_ordered_and_attributed() {
        let mut previous = -1.0_f64;
        for Reply(at, speaker, text) in REPLIES {
            assert!(
                *at > previous,
                "reply starts must increase: {at} after {previous}"
            );
            assert!(
                *speaker < SPEAKER_NAMES.len(),
                "unknown speaker index {speaker}"
            );
            assert!(!text.trim().is_empty(), "empty reply at {at}");
            previous = *at;
        }
    }

    /// The score is what the meeting screen shows first, so the example must land in a
    /// believable middle: good enough to look real, imperfect enough to be worth reading.
    #[test]
    fn example_score_is_plausible() {
        let topics = topics();
        let commitments = commitments();
        let score = compute_score(
            &topics.agenda,
            &commitments.commitments,
            threads_risks().open_threads.len(),
        );
        assert!(
            (55..=90).contains(&score.total),
            "example score {} is outside the believable range",
            score.total
        );
    }
}
