/**
 * Canonical markdown for meeting exports.
 *
 * Every export format is a rendering of the string these helpers produce, so the
 * Markdown, PDF and DOCX outputs cannot drift apart. The Rust side
 * (`src-tauri/src/export/`) only converts and writes.
 */

// Type-only so this module stays runtime-dependency-free and can be unit
// tested directly with node:test.
import type { Summary, Transcript } from '@/types';

export type ExportScope = 'summary' | 'transcript' | 'both';
export type ExportFormat = 'md' | 'pdf' | 'docx';

export interface ExportMeeting {
  id: string;
  title: string;
  created_at: string;
}

export const SCOPE_LABELS: Record<ExportScope, string> = {
  summary: 'Summary',
  transcript: 'Transcript',
  both: 'Summary + Transcript',
};

export const FORMAT_LABELS: Record<ExportFormat, string> = {
  md: 'Markdown',
  pdf: 'PDF',
  docx: 'Word',
};

/**
 * Recording-relative `[MM:SS]`, matching what the copy-to-clipboard action
 * produces. Transcripts recorded before `audio_start_time` existed fall back to
 * their stored wall-clock timestamp.
 */
export function formatTranscriptTime(
  seconds: number | undefined,
  fallbackTimestamp: string
): string {
  if (seconds === undefined || !Number.isFinite(seconds)) {
    return fallbackTimestamp;
  }
  const totalSecs = Math.max(0, Math.floor(seconds));
  const mins = Math.floor(totalSecs / 60);
  const secs = totalSecs % 60;
  return `[${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}]`;
}

/** Formats a stored ISO timestamp for the document header. */
export function formatMeetingDate(createdAt: string): string {
  const date = new Date(createdAt);
  if (Number.isNaN(date.getTime())) {
    return createdAt;
  }
  return date.toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

/**
 * Normalises a summary into markdown.
 *
 * Summaries generated by the current pipeline already carry a `markdown` field;
 * older meetings hold the legacy `{ title, blocks }` section shape, which is
 * converted here rather than being lost.
 */
export function summaryToMarkdown(summary: Summary | null): string {
  if (!summary) return '';

  const maybeMarkdown = (summary as unknown as { markdown?: string }).markdown;
  if (typeof maybeMarkdown === 'string' && maybeMarkdown.trim()) {
    return maybeMarkdown.trim();
  }

  const ignoredKeys = new Set(['markdown', 'summary_json', '_section_order', 'MeetingName']);

  return Object.entries(summary)
    .filter(([key]) => !ignoredKeys.has(key))
    .map(([, section]) => {
      if (!section || typeof section !== 'object') return '';
      const typed = section as { title?: string; blocks?: Array<{ content?: string }> };
      if (!Array.isArray(typed.blocks)) return '';

      const body = typed.blocks
        .map((block) => (block?.content ?? '').trim())
        .filter(Boolean)
        .map((content) => `- ${content}`)
        .join('\n');

      if (!body) return '';
      return `## ${typed.title ?? 'Section'}\n\n${body}`;
    })
    .filter(Boolean)
    .join('\n\n')
    .trim();
}

/** Renders transcript segments as timestamped markdown lines. */
export function transcriptsToMarkdown(transcripts: Transcript[]): string {
  return transcripts
    // Filter before adding the timestamp: afterwards every line looks non-empty
    // and a blank segment would leave a stray "[01:30]" behind.
    .filter((t) => t.text?.trim())
    .map((t) => `${formatTranscriptTime(t.audio_start_time, t.timestamp)} ${t.text.trim()}`)
    .join('\n\n')
    .trim();
}

export interface BuildExportMarkdownArgs {
  meeting: ExportMeeting;
  title: string;
  scope: ExportScope;
  summary: Summary | null;
  /** Markdown pulled straight from the editor; preferred over `summary`. */
  summaryMarkdown?: string;
  transcripts: Transcript[];
}

/**
 * Assembles the document handed to the Rust exporter.
 *
 * Throws when the requested scope has no content, so the caller can surface a
 * message instead of writing an empty file.
 */
export function buildExportMarkdown({
  meeting,
  title,
  scope,
  summary,
  summaryMarkdown,
  transcripts,
}: BuildExportMarkdownArgs): string {
  const heading = (title || meeting.title || 'Meeting').trim();
  const parts: string[] = [
    `# ${heading}`,
    `**Date:** ${formatMeetingDate(meeting.created_at)}  \n**Exported:** ${formatMeetingDate(
      new Date().toISOString()
    )}`,
    '---',
  ];

  const wantsSummary = scope === 'summary' || scope === 'both';
  const wantsTranscript = scope === 'transcript' || scope === 'both';

  const resolvedSummary = (summaryMarkdown?.trim() || summaryToMarkdown(summary)).trim();
  const resolvedTranscript = transcriptsToMarkdown(transcripts);

  if (wantsSummary) {
    if (!resolvedSummary) {
      throw new Error('No summary content available to export');
    }
    // `both` needs an explicit heading; a summary-only document is already
    // titled by the meeting name.
    parts.push(scope === 'both' ? `## Summary\n\n${resolvedSummary}` : resolvedSummary);
  }

  if (wantsTranscript) {
    if (!resolvedTranscript) {
      throw new Error('No transcript content available to export');
    }
    parts.push(`## Transcript\n\n${resolvedTranscript}`);
  }

  return `${parts.join('\n\n')}\n`;
}

/** Default filename offered in the save dialog, without an extension. */
export function buildExportFileName(
  title: string,
  createdAt: string,
  scope: ExportScope
): string {
  const date = new Date(createdAt);
  const datePart = Number.isNaN(date.getTime())
    ? ''
    : `-${date.toISOString().slice(0, 10)}`;

  const scopePart =
    scope === 'both' ? '-full' : scope === 'transcript' ? '-transcript' : '-summary';

  const base = (title || 'meeting').trim().replace(/\s+/g, ' ');
  return `${base}${datePart}${scopePart}`;
}
